Issue #1236 Add frame_screens node script
pg-irc/pathways-frontend pull request #1237
Opened 2020-07-31 04:59 UTC by niko-pg

Add frame_screens node script that automates the generation of screenshots in different language and platforms.

2020-08-13 18:17 UTC, tomy-pg commented on bin/frame_screens/cleanup.sh
> +done
Thanks for this.

2020-08-24 16:37 UTC, rasmus-storjohann-PG commented on bin/frame_screens/config.json
> +        "pa": "MuktaMahee-Regular.ttf",
Where did you find these files? How are they licensed?

2020-08-24 16:43 UTC, rasmus-storjohann-PG commented on bin/frame_screens/config.json
> +        "ar": "Avenir-Black.ttf"
It would be pretty natural to squash this commit with the previous one

2020-08-24 20:53 UTC, tomy-pg commented on bin/frame_screens/config.json
> +        "pa": "MuktaMahee-Regular.ttf",
Avenir is a font family I retrieved from @cherrielam. 
MuktaMahee is from Google fonts. They are open source fonts. https://developers.google.com/fonts/faq

2020-09-02 21:33 UTC, rasmus-storjohann-PG requested changes
Some old comments that I never submitted

2020-09-02 21:36 UTC, merged