Feature/issue 1042 new org detail page
pg-irc/pathways-frontend pull request #1255
Opened 2020-08-27 17:27 UTC by ian-lin-PG

2020-09-02 17:46 UTC, ian-lin-PG commented on src/validation/services/types.ts
> +    readonly organizationId: string;
The validation happens at the ajv stage, as long as the struct and object share the same structure it will pass. I changed both in this case to avoid the test from failing. I can add in a specific test for testing `organizationID` or more likely create a test that checks every field.

2020-09-03 18:45 UTC, rasmus-storjohann-PG approved these changes
I made some additional tweaks to the PR. It would really help if you figure out how to get linter errors to show up in your IDE.

2020-09-03 18:45 UTC, rasmus-storjohann-PG commented on src/stores/__tests__/services.test.ts
> +            expect(storeService.lastVerifiedDate).toEqual(aSearchService.lastVerifiedDate);
Single responsibility also applies to tests, where it usually means that each test should test just one thing, meaning that ideally a test only have one assert statement. Often it makes sense to have more than one, but this approach of having this many is a code smell. In this case, there is a very simple change that can be made to `expect(storeService).toEqual(aSearchService);`, but in other cases, a deeper rethink of the test can often make for real improvements...

2020-09-03 18:45 UTC, rasmus-storjohann-PG commented on src/components/organizations/organization_detail_component.tsx
> +    });
My review comment here wasn't very clear, this is what I had in mind

2020-09-29 16:45 UTC, tomy-pg requested changes

2020-09-29 16:45 UTC, tomy-pg commented on src/validation/organizations/__tests__/validation.tests.ts
> +        it('returns alert', () => {
do you mean that it `returns a valid organization`?

2020-09-29 16:52 UTC, rasmus-storjohann-PG requested changes
Just some small things to fix

2020-09-29 16:52 UTC, rasmus-storjohann-PG commented on src/components/organizations/organization_detail_component.tsx
> +const AboutContactDetails = (props: AboutOrganizationProps): JSX.Element => {
We have a really simple naming convention for props and actions passed in to components, for `FooComponent`, they should be called `FooComponentProps` and `FooComponentActions`. Following conventions like this makes the code much simpler to work with.

2020-09-29 16:52 UTC, rasmus-storjohann-PG commented on src/components/organizations/organization_detail_component.tsx
> +const AboutTab = (props: AboutOrganizationProps): JSX.Element => (
Naming convention for props applies here too, I would probably rename this to AboutTabComponent and AboutTabComponentProps

2020-09-29 16:52 UTC, rasmus-storjohann-PG commented on src/components/organizations/organization_detail_connected_component.tsx
> +});
Thanks, this is better, try to stay consistent with using this form when possible.

2020-09-29 16:52 UTC, rasmus-storjohann-PG commented on src/stores/user_experience/index.ts
> +            });
This kind of change should *always* be unit tested.

2020-09-29 16:52 UTC, rasmus-storjohann-PG commented on src/stores/__tests__/services.test.ts
> +            expect(storeService).toEqual(aSearchService);
A bit of advice when changing a test like this: Keep in mind that a common bug that can happen in tests is that tests pass when they ought to fail. A very difficult bug to find. So it's a good habit when making this kind of change to break the production code to make sure that the test works, i.e. that it fails when it ought to. Did you try that?

2020-09-29 16:52 UTC, rasmus-storjohann-PG commented on src/validation/organizations/__tests__/validation.tests.ts
> +        it('returns alert', () => {
alert? Seems like a copy-paste error to me

2020-09-29 16:52 UTC, rasmus-storjohann-PG commented on src/validation/organizations/__tests__/validation.tests.ts
> +                email: aString(),
We have generators for these, aWebUrl() or something

2020-09-29 16:52 UTC, rasmus-storjohann-PG commented on src/validation/organizations/__tests__/validation.tests.ts
> +        it('returns empty array', () => {
it accepts empty array?

2020-09-29 18:02 UTC, ian-lin-PG commented on src/validation/organizations/__tests__/validation.tests.ts
> +                email: aString(),
Currently in the code base we use `aString()` for all test website and emails.

2020-09-29 18:08 UTC, ian-lin-PG commented on src/validation/organizations/__tests__/validation.tests.ts
> +        it('returns empty array', () => {
This is a defining difference between organizations and services. Currently services could be represented as a list of services (search, topic recommendations) or an individual service (service detail). 

Current issue is only about representing an organization (organization detail), down the road if we do include organization search we might have an empty array. Might be too far ahead for this PR.

2020-09-29 22:23 UTC, ian-lin-PG commented on src/stores/__tests__/services.test.ts
> +            expect(storeService).toEqual(aSearchService);
I added in a check for the number of fields to be expected, this will fail next time if we add or remove fields to the humanServiceData object. This isn't perfect for when a commit adds in and remove same number of fields. I wasn't able to cause the test to fail due to the payload validation on the SaveServiceAction. Other suggestions are welcome.

2020-09-30 19:27 UTC, merged