Feature/issue 1262 back button for feedback sends to wrong screen
pg-irc/pathways-frontend pull request #1274
Opened 2020-09-10 23:05 UTC by tomy-pg

2020-09-10 23:21 UTC, rasmus-storjohann-PG commented on src/components/feedback/contact_information_component.tsx
> +        goBackToServiceDetailOnFeedbackSubmit(memoryHistory);
name should be popFeedbackElementsFromHistory

2020-09-10 23:24 UTC, rasmus-storjohann-PG commented on src/application/__tests__/routing.test.ts
> +        expect(history.location.pathname).toBe(serviceDetailPath);
Test that you have these `firstRegularPath, secondRegularPath, serviceDetailPath` all in order in the history

2020-09-10 23:26 UTC, rasmus-storjohann-PG commented on src/application/routing.ts
> +};
Rename to popFeedbackPathsFromHistory

2020-09-10 23:40 UTC, tomy-pg commented on src/application/routing.ts
> +    while (R.findLast(pathMatchesFeedbackRoute, memoryHistory.entries) && R.not(R.isEmpty(memoryHistory.entries))) {
test to see if I can drop `R.not(R.isEmpty(memoryHistory.entries)`

2020-09-10 23:48 UTC, rasmus-storjohann-PG requested changes
Found some things after all, make sure you cover the three different feedback flows, remove service, other feedback and service feedback

2020-09-10 23:48 UTC, rasmus-storjohann-PG commented on src/application/__tests__/routing.test.ts
> +    });
I don't think this test is needed anymore? If you keep it, I think the name of the test needs to change.

2020-09-10 23:48 UTC, rasmus-storjohann-PG commented on src/application/__tests__/routing.test.ts
> +    });
Same with this test, goBack() is not your function (right?) so both of these tests just show that it goes back one step, which is the same functionality in each test.

2020-09-10 23:48 UTC, rasmus-storjohann-PG commented on src/application/__tests__/routing.test.ts
> +    });
This test is also redundant I think.

2020-09-10 23:48 UTC, rasmus-storjohann-PG commented on src/application/routing.ts
> +    pathMatchesAnyRoute(location.pathname, [Routes.OtherFeedback, Routes.ContactInformation])
Editable service detail and remove service routes need to be in here too I think?

2020-09-10 23:48 UTC, rasmus-storjohann-PG commented on src/components/header_button/back_button_component.tsx
> +// TO DO remove history prop.
don't forget

2020-09-11 00:07 UTC, tomy-pg commented on src/application/routing.ts
> +    pathMatchesAnyRoute(location.pathname, [Routes.OtherFeedback, Routes.ContactInformation])
These two screens are covered.
the `EditableServiceDetail` screen is equivalent to Routes.ServiceDetail. Its a state change that makes that screen editable, we don't change routes when this occurs. 
As well the `RemoveService` screen is equivalent to Routes.OtherFeedback.

2020-09-11 00:08 UTC, tomy-pg commented on src/application/routing.ts
> +    pathMatchesAnyRoute(location.pathname, [Routes.OtherFeedback, Routes.ContactInformation])
I will add a test to include the editableServiceDetail flow.

2020-09-11 00:24 UTC, tomy-pg commented on src/application/routing.ts
> +};
Fixed

2020-09-11 00:24 UTC, tomy-pg commented on src/application/__tests__/routing.test.ts
> +        expect(history.location.pathname).toBe(serviceDetailPath);
Fixed

2020-09-11 01:44 UTC, rasmus-storjohann-PG requested changes
Get Ian's help tomorrow to do a very careful QA pass on this, then you can merge it and push to staging.

2020-09-11 01:44 UTC, rasmus-storjohann-PG commented on src/application/__tests__/routing.test.ts
> +        expect(history.entries[2].pathname).toBe(serviceDetailPath);
Didn't expect this unless serviceDetailPath is the last element before editableServiceDetailFeedbackPath in the initialPathEntries

2020-09-11 01:44 UTC, rasmus-storjohann-PG commented on src/components/header_button/back_button_component.tsx
> +// TO DO remove history prop.
You can remove the comment now ;-)

2020-09-11 17:58 UTC, ian-lin-PG approved these changes

2020-09-11 17:59 UTC, merged