Feature/issue 1259 location spoofing easter egg
pg-irc/pathways-frontend pull request #1278
Opened 2020-09-15 16:49 UTC by ian-lin-PG

2020-09-15 18:01 UTC, tomy-pg requested changes
A few small things. Still need to QA on device.

2020-09-15 18:01 UTC, tomy-pg commented on src/components/help/help_component.tsx
> +    }
ts-lint:
`missing whitespace`
`missing semi-colon`

2020-09-15 19:03 UTC, rasmus-storjohann-PG requested changes

2020-09-15 22:26 UTC, rasmus-storjohann-PG requested changes

2020-09-15 22:26 UTC, rasmus-storjohann-PG commented on src/components/help/help_component.tsx
> +        props.dispatchServicesRequest(props.topic, newManualUserLocation)
`        props.dispatchServicesRequest(props.topic, {latLong: props.customLatLong})`

2020-09-15 22:26 UTC, rasmus-storjohann-PG commented on src/components/search/search_component.tsx
> +            const re = /[-+]?\d.*\d/;
```
/ *([+-]?\d*\.\d+) *\, *([+-]?\d*\.\d+)/
```

2020-09-15 22:31 UTC, rasmus-storjohann-PG commented on src/components/topics/topic_detail_component.tsx
> +            label: 'custom',
Refactor: Rename label to humanReadableLocation

2020-09-15 23:02 UTC, rasmus-storjohann-PG commented on src/components/topics/topic_detail_component.tsx
> +    else {
Still not right, our convetion is to put { on its own line. No big deal.

2020-09-15 23:02 UTC, rasmus-storjohann-PG commented on src/sagas/post_push_notification_token.ts
> +    const result: APIResponse = yield call(putPushNotificationToken, token.data, locale, PATHWAYS_API_KEY);
That doesn't always work, test to see that it's not broken.

2020-09-15 23:04 UTC, rasmus-storjohann-PG commented on src/components/search/search_component.tsx
> +            const parsedLatLong = location.match(re);
And what happens if the input string doesn't match the RE?

2020-09-16 00:07 UTC, rasmus-storjohann-PG requested changes
Sorry, I found one more thing. @tomy-pg did you check that when you tested?

2020-09-16 00:07 UTC, rasmus-storjohann-PG commented on src/components/search/search_component.tsx
> +                alert(`Custom LatLong enabled, {lat: ${parsedLatLong[1]}, lng: ${parsedLatLong[2]}}`);
I'm really really sorry that I only noticed this now ... this is the PR that never ends.

So a very common problem with latlong is that we can get the two numbers switched. And I think they are switched here? Because I *believe* the input string will conventionally be in the order long,lat. So I *think* that means that the indeces 1 and 2 need to be swapped around?

2020-09-16 17:11 UTC, ian-lin-PG commented on src/components/search/search_component.tsx
> +                alert(`Custom LatLong enabled, {lat: ${parsedLatLong[1]}, lng: ${parsedLatLong[2]}}`);
Putting [this](https://stackoverflow.com/questions/18636564/lat-long-or-long-lat#:~:text=2%20Answers&text=You%20are%20correct%2C%20there%20is,y%20order%20is%20ususally%20prefered.) here as a reference.

The gist is that for mathematical purpose longitude (x) comes before latitude (y), this is due to how they are represented on mathematical formulas. For representation purpose latitude comes before longitude, due to the standard developed before longitude can be reliably measured.

2020-09-16 17:48 UTC, merged