Feature/issue 1260 org data
pg-irc/pathways-frontend pull request #1301
Opened 2020-10-21 17:13 UTC by ian-lin-PG

2020-10-21 17:35 UTC, tomy-pg requested changes

2020-10-21 17:35 UTC, tomy-pg commented on src/components/organizations/organization_detail_component.tsx
> +    }
Instead of getting organizations this way, the api call can be done through a `useEffect` with an empty dependency if you want to get the organization only on component mount. Optionally you can use `organization.id` as a dependency if you decide this is needed as well.

2020-10-21 17:35 UTC, tomy-pg commented on src/components/organizations/organization_detail_component.tsx
> +            body={props.organization.description}
If you are replacing the test organization with organization state in this commit, I expected to see you using the organization state as opposed to the organization prop.

2020-10-21 17:35 UTC, tomy-pg commented on src/components/organizations/organization_detail_component.tsx
> +    readonly organization: HumanOrganizationData;
What will you be using this prop for?

2020-10-21 17:35 UTC, tomy-pg commented on src/api/index.ts
> +    return createAPIResponse(response);
Nice. Looking to see `Ajv` validation next. (Similar to what we did with search)

2020-10-21 18:23 UTC, rasmus-storjohann-PG requested changes
Looking good!

2020-10-21 18:23 UTC, rasmus-storjohann-PG commented on src/components/organizations/organization_detail_component.tsx
> +    const [organization, setOrganization]: readonly [HumanOrganizationData, (org: HumanOrganizationData)=> void] = useState(undefined);
Make sure the comment above doesn't get disconnected from whatever it was commenting on

2020-10-21 18:23 UTC, rasmus-storjohann-PG commented on src/components/organizations/organization_detail_component.tsx
> +    }, []);
`useEffect()` gotcha is to forget to include things in the dependency list. I think you need to include `getOrganization` and `setOrganization` here.

2020-11-05 22:09 UTC, rasmus-storjohann-PG requested changes
Lots of good work here. I have some suggestions for improvements. Make sure your linter is working and using the rules from the repo.

2020-11-05 22:09 UTC, rasmus-storjohann-PG commented on src/components/organizations/organization_service_list_component.tsx
> +                    ...props
I would prefer that you spelled out the props being passed here rather than using `...`, it's only two I think...

2020-12-02 22:18 UTC, rasmus-storjohann-PG requested changes
Hey @ian-lin-PG this is really really good work. I had a lot of fun reviewing this PR. I do suggest some changes, but almost all of them should be pretty trivial. The ones that you think would be time consuming to fix, let's discuss. Well done.

2020-12-02 22:18 UTC, rasmus-storjohann-PG commented on src/stores/organization/action.ts
> +import { HumanOrganizationData } from '../../validation/organizations/types';
Rename file to plural "actions.ts"

2020-12-02 22:18 UTC, rasmus-storjohann-PG commented on src/validation/organizations/types.ts
> +    readonly organizationTab: number;
The tab should actually go in the user experience store, not the organization store.

2020-12-02 22:18 UTC, rasmus-storjohann-PG commented on src/validation/search/__tests__/helpers/search_schema.ts
> +export const anSearchService = (): any => ({
typo: "aSearchService"

2020-12-02 22:18 UTC, rasmus-storjohann-PG commented on src/validation/services/types.ts
> +    readonly servicesByOrganization: ServicesForOrganization;
Inconsistent naming, "by" vs. "for", I prefer "for".

2020-12-02 23:45 UTC, ian-lin-PG commented on src/components/organizations/organization_detail_component.tsx
> +    }
I realized the organizationIds will always match since they are both derived from the same location, so I deleted this logic.

2020-12-02 23:47 UTC, ian-lin-PG commented on src/components/organizations/organization_detail_component.tsx
> +    const [organization, setOrganization]: readonly [HumanOrganizationData, (org: HumanOrganizationData)=> void] = useState(undefined);
Removed the logic once we replaced the native-base tab logic.

2020-12-02 23:48 UTC, ian-lin-PG commented on src/components/organizations/organization_detail_component.tsx
> +    }, []);
Avoided the useEffect here entirely and have the API call through saga instead.

2020-12-02 23:53 UTC, ian-lin-PG commented on src/components/loading_screen/loading_service_list_component.tsx
> +            <LoadingServiceListItemComponent />
The loading screen on organization page had white space at the bottom. This is because most other loading screen thus far cover part of the page instead of the entire page. I am open to suggestion such that the loading screen looks less odd.

2020-12-03 21:03 UTC, ian-lin-PG commented on src/components/services/service_detail_component.tsx
> +                            history={props.history}
I think I added the open organization action that starts the cascade of API calls.

2020-12-03 21:11 UTC, ian-lin-PG commented on src/components/organizations/organization_service_list_component.tsx
> +    }, [props.organizationServicesOffset, props.services, flatListRef]);
We use the same pattern for all the service list offsets now.

2020-12-03 22:30 UTC, ian-lin-PG commented on src/components/organizations/organization_detail_component.tsx
>              // TODO Issue #1080 When organization detail page is online connect the following 2 states to the store/persisted data
I been thinking about this. Technically only topic detail are in Markdown format which has the link out functionality. For services and organization description that are usually plain test the link alert and hide link alert are never used.

2020-12-03 23:18 UTC, ian-lin-PG commented on src/sagas/services.ts
> +}
That is true, even if users are unlikely to notice the extra network requests. Checking the organization store before triggering the action might be too much overhead. Currently don't see a beautiful solution...

2020-12-04 00:13 UTC, ian-lin-PG commented on src/components/organizations/org_tab_swticher.tsx
> +        {...tabBarProps}
`type TabBarProps = SceneRendererProps & NavigationStateRoute;` 
`import { TabView, Route, NavigationState, SceneRendererProps, TabBar } from 'react-native-tab-view';`
The tabBarProps are actually references to the library, I think we only override the library with the few lines underneath.

2020-12-04 00:28 UTC, ian-lin-PG commented on src/components/search/api/fetch_search_results_from_query.ts
> +    }
Created a helper to build the request.

2020-12-04 22:47 UTC, ian-lin-PG commented on src/stores/__tests__/services.test.ts
> +        });
The organizationId is tested in `organization.test.ts` file, I do agree it's quite odd to have the test separated like this.

2020-12-04 23:32 UTC, ian-lin-PG commented on src/components/organizations/org_tab_swticher.tsx
> +    const renderScene = ({ route }: { readonly route: Route}): JSX.Element => {
I took a peek into the documentation, haven't been able to pass in extra parameters into the `renderScene` of the TabView component.

2020-12-07 17:21 UTC, rasmus-storjohann-PG commented on src/stores/__tests__/user_experience.test.ts
> +    });
Nice to see the tests. When you get used to writing the tests along with the code rather than afterwards, I promise you that you will enjoy writing them.

2020-12-07 18:52 UTC, tomy-pg commented on src/components/organizations/organization_service_list_component.tsx
> +    }, [props.organizationServicesOffset, props.services, flatListRef]);
This looks good

2020-12-07 19:37 UTC, tomy-pg requested changes

2020-12-07 19:37 UTC, tomy-pg commented on src/sagas/services.ts
> +}
You can use redux-saga's `select()` here if you want. This is not always encouraged to do as it is preferred that saga's be autonomous.

However, I see that in `updateServicesOrganization` you are using this already for `bookmarkedServicesIds`. 
So you can also use a services for organization selector to make the check if the service already exists before making the network request.

2020-12-07 19:37 UTC, tomy-pg commented on src/components/organizations/organization_component.tsx
> +                    <View padder style={{ flex: 1 }}>
This `View` affects how the UX of the services list, especially when the services list is not fully populated. It makes it such that there are two different scrolling views on the page and the service card is background and dividers are not completely extended to the full width of the screen. 

![Screen Shot 2020-12-07 at 11 22 31 AM](https://user-images.githubusercontent.com/47794846/101395514-e9887100-387e-11eb-8b54-848464056d59.png)


I think you can remove this `View` and add padding to the different components used here.

2020-12-07 19:37 UTC, tomy-pg commented on src/components/organizations/organization_service_list_component.tsx
> +            ListHeaderComponent={<View />}
`Flatlist's` `initialNumToRender` property needs to be declared. The UX for when a user clicks on a service detail and then clicks back to the service list will not work properly without this. 

This is an optimization by React-Native that we have to override since by default, they set the initial batch of items to render to be 20. For our case, if a user navigates to any service detail where its position on the list is beyond the initial 20 and then wants to go back to the service list, their previous scroll-offset will not exist. 

`initialNumToRender={props.organizationServicesOffset ? services.length : 20}`

2020-12-07 23:10 UTC, tomy-pg requested changes

2020-12-07 23:10 UTC, tomy-pg commented on src/components/organizations/organization_component.tsx
> +                    <DescriptorComponent descriptor={<Trans>ORGANIZATION</Trans>} />
for the components in this file starting here, more horizontal padding will need to be added since `padder` was removed and the native-base `View` is no longer used. 

As well, watch the alignment of the Title components and the service detail components. See mocks [here](https://app.zeplin.io/project/5bc7bfa42e72260acb03aa86/screen/5d929aa5a78fc061803c87ca)

2020-12-09 22:37 UTC, tomy-pg approved these changes

2020-12-09 22:37 UTC, merged