Feature/issue 1323 organization page handle offline
pg-irc/pathways-frontend pull request #1347
Opened 2021-01-16 01:34 UTC by ian-lin-PG

2021-01-18 22:38 UTC, rasmus-storjohann-PG requested changes
Really nice work @ian-lin-PG , we can discuss some of the changes I suggest here, especially around the valid/invalid store.

2021-01-19 19:09 UTC, ian-lin-PG commented on src/validation/organizations/types.ts
> +}
The validation types.ts doesn't seem to accept references for their type definitions. See also `/Users/ianlin/Desktop/PeaceGeeks/pathways-frontend/src/validation/services/types.ts`. Trying to change the type from strings causes the builder to fail as well.

2021-01-20 17:54 UTC, rasmus-storjohann-PG requested changes
Just minor issues with naming and such, coming together nicely

2021-01-20 17:54 UTC, rasmus-storjohann-PG commented on src/application/constants.ts
> +export const LOAD_ORGANIZATION_FAILURE = 'LOAD_ORGANIZATION_FAILURE';
Yes this is better

2021-01-20 17:54 UTC, rasmus-storjohann-PG commented on src/stores/__tests__/organization.test.ts
>          it('updates the store with the new organization in addition to old Organization', () => {
The name of the test indicates that you will test for the old org being there as well, but there is no assert for that

2021-01-20 17:54 UTC, rasmus-storjohann-PG commented on src/stores/__tests__/organization.test.ts
>              expect(storeOldOrganization).toEqual(oldOrganizationBuilder.build());
You're testing the behaviour of the unit under test, which is the reducer. Here you are asserting on what went into the reducer as input, that is not relevant to the test.

2021-01-20 17:54 UTC, rasmus-storjohann-PG commented on src/stores/__tests__/organization.test.ts
> +        it('updates the store with the new organization in addition to old Organization', () => {
wrong test name, copy paste error probably

2021-01-20 17:54 UTC, rasmus-storjohann-PG commented on src/stores/__tests__/organization.test.ts
> +            expect(store.organizationStatus.type).toEqual(constants.ERROR_ORGANIZATION);
Need a test for the error state being added to the store too, I think. Note that if you did actual TDD, you would naturally write all the necessary tests, and you would probably do so in less time.

2021-01-20 17:54 UTC, rasmus-storjohann-PG commented on src/stores/organization/actions.ts
> +export const errorOrganization = (organizationId: string, errorMessageType: Errors) => (
Model your names on how you would talk about this to another human. "error organization" does not fit in a normal English sentence. How about something like "loading organization failed" or "organization loading failure", better? Same with the other names.

2021-01-20 20:54 UTC, merged