Feature/issue #1344 build ux for review this service
pg-irc/pathways-frontend pull request #1349
Opened 2021-01-19 23:08 UTC by tomy-pg

2021-01-20 02:38 UTC, rasmus-storjohann-PG requested changes
Really good work, and quick! You have over-learned the thing about small commits though, there are too many!

2021-01-20 02:38 UTC, rasmus-storjohann-PG commented on src/components/reviews/ratings_component.tsx
> +            }, props.iconsList)}
Looking to create some consistency on how we write functions that just do a return, let's stick with the shorter form using `()` and no return:
```ts
            R.map((icon: RatingIcon): JSX.Element => (
                    <RatingIconComponent
                        key={icon.name}
                        isChosen={icon.value === props.rating}
                        icon={icon}
                        onPress={(): void => props.chooseRating(icon.value)}
                    />
                ), props.iconsList)}
```

2021-01-20 02:38 UTC, rasmus-storjohann-PG commented on src/components/reviews/service_review_component.tsx
> +            />
The copy on this modal should ideally be adapted to the review function. Not bad enough to break the string freeze, but probably create an issue for it so we don't forget. Currently is says "Discard the changes you suggested?" which is appropriate for feedback but not review.

2021-01-20 02:38 UTC, rasmus-storjohann-PG commented on src/components/reviews/service_review_component.tsx
> +            </KeyboardAwareScrollView>
Slight UX glitch where it doesn't look like it can scroll all the way down ... I think we've already seen this elsewhere and it can't be fixed, IIRC.

2021-01-20 21:54 UTC, tomy-pg commented on src/components/reviews/service_review_component.tsx
> +            />
Issue has been created, see: https://github.com/pg-irc/pathways-frontend/issues/1352

2021-01-20 21:56 UTC, tomy-pg commented on src/components/reviews/service_review_component.tsx
> +            </KeyboardAwareScrollView>
I can give this another look over. I recall this bug from the work we did with `Feedback` inputs.

2021-01-20 23:35 UTC, tomy-pg commented on src/application/routing.ts
> +    }
Great find. Fixed this for `Feedback` as well.

2021-01-21 00:26 UTC, rasmus-storjohann-PG commented on src/application/routing.ts
> +    while (pathMatchesFeedbackRoute(R.last(memoryHistory.entries))) {
yup

2021-01-21 00:39 UTC, merged