Feature/issue 1345 wire-up airtable for service reviews
pg-irc/pathways-frontend pull request #1354
Opened 2021-01-26 19:38 UTC by tomy-pg

2021-01-27 18:56 UTC, rasmus-storjohann-PG requested changes
Nice work, just a few comments and requested changes

2021-01-27 18:56 UTC, rasmus-storjohann-PG commented on src/sagas/reviews.ts
> +    return buildUrl('https://api.airtable.com', { path: `v0/${AIRTABLE_BASE_ID}/${AIRTABLE_TABLE_SERVICES_REVIEWS_ID}` });
Just be aware of the issues raised here https://stackoverflow.com/a/3369494

2021-01-27 18:56 UTC, rasmus-storjohann-PG commented on src/sagas/reviews.ts
> +const buildRequestInit = (serviceReviewJSON: string): RequestInit => {
`RequestInit` is a bit of a weird name. It's an abbreviation for one. How about ReviewPostRequest?

2021-01-27 18:56 UTC, rasmus-storjohann-PG commented on src/selectors/locale/select_locale_code.ts
> +    return toSelectorLocale(store).code;
You can just do `return store.code` here I think

2021-01-27 18:56 UTC, rasmus-storjohann-PG commented on src/sagas/reviews.ts
> +        yield put(clearReview());
Do you really need these two actions? Redux is great for expressing situations where one action should have more than one consequence in different parts of the store. It feels like that's what's really going on here, that at the end of this flow, you want to dispatch one action that will cause two distinct changes to the store. The code here should just worry about the actions to emit, the reducers are then responsible for responding to those actions, thereby separating those concerns.

2021-01-27 18:56 UTC, rasmus-storjohann-PG commented on src/components/reviews/service_review_component.tsx
> +        backToServiceDetailOnServiceReviewDiscard(memoryHistory);
I would prefer that you do the rename in the same commit. I would not prefer that if the function you're renaming was used in lots and lots of places, since that would make the other changes in the same commit hard to see, but I don't believe that is the case here.

2021-01-27 18:56 UTC, rasmus-storjohann-PG commented on src/components/services/service_detail_component.tsx
> +                            isSendingFeedbackOrReview={props.isSendingFeedback || props.isSendingReview}
So the question here is, should this component know about the fact that there are two different things that might be in the process of being sent? If the component should not know, when who should? Would it make sense to have a selector that knows about the details of the store (like all selectors do) and permit the connected component and this code to just worry about "something" being sent?

2021-01-27 18:56 UTC, rasmus-storjohann-PG commented on src/sagas/reviews.ts
> +        Sentry.captureException(error);
good call, I haven't had Sentry on my horizon enough

2021-01-27 19:12 UTC, rasmus-storjohann-PG commented
I've reviewed the deploy PR and it's ready to go in. Suggested a name change, but it's optional, not a big deal.

2021-01-28 17:49 UTC, tomy-pg commented on src/sagas/reviews.ts
> +const buildRequestInit = (serviceReviewJSON: string): RequestInit => {
I am happy to make this change. I originally named it after the interface the function returns.

2021-01-28 17:50 UTC, tomy-pg commented on src/components/reviews/service_review_component.tsx
> +        backToServiceDetailOnServiceReviewDiscard(memoryHistory);
Okay that makes sense!

2021-01-28 17:50 UTC, tomy-pg commented on src/sagas/reviews.ts
> +const buildRequestInit = (serviceReviewJSON: string): RequestInit => {
Okay, I am happy to do this. I originally named this function based on the interface being returned.

2021-01-28 19:40 UTC, merged