Feature/issue 1348 rate this service and banner
pg-irc/pathways-frontend pull request #1357
Opened 2021-02-01 20:44 UTC by tomy-pg

2021-02-02 19:30 UTC, rasmus-storjohann-PG requested changes
Really good work, readable code.

2021-02-02 19:30 UTC, rasmus-storjohann-PG commented on src/components/services/service_detail_component.tsx
> +    isVisible ? <DividerComponent /> : <EmptyComponent />
`DividerComponent` is ours, you can add an `isVisible` prop on it that defaults to true so you don't have to touch all it's call sites.

2021-02-02 19:30 UTC, rasmus-storjohann-PG commented on src/components/bookmarks/service_bookmarks_component.tsx
> +import { ThankYouMessageOrEmptyComponent } from '../services/thank_you_message_or_empty_component';
It's pretty natural for a component to have an isVisible property without that having to be represented in the name of the component, so I would prefer the simpler name of `ThankYouMessage` here.

2021-02-02 19:30 UTC, rasmus-storjohann-PG commented on src/components/scroll_to_offset_with_timeout.ts
> +export const scrollToOffsetWithTimeout = (flatListRef: React.MutableRefObject<FlatList>, offset: number): void => {
How about if we consider the fact that this function uses a timeout to be an implementational detail that the caller has no need to know about? In that case, this function should just be called `scrollToOffset()`, which is nicer

2021-02-02 19:30 UTC, rasmus-storjohann-PG commented on src/components/search/search_results_component.tsx
> +              }, 0);
We should use the helper function that you created here as well, no?

2021-02-02 19:30 UTC, rasmus-storjohann-PG commented on src/components/search/search_results_component.tsx
> +        props.saveService(service);
Here I find myself thinking, what do you mean, save service? Does it end up being persisted in the device, or just the id tucked away somewhere? This function can probably just be renamed to fix this problem.

2021-02-02 19:31 UTC, rasmus-storjohann-PG commented on src/components/bookmarks/service_bookmarks_component.tsx
> +import { ThankYouMessageOrEmptyComponent } from '../services/thank_you_message_or_empty_component';
So the improved DividerComponent also does not need to be renamed

2021-02-02 22:56 UTC, tomy-pg commented on src/components/reviews/service_review_component.tsx
> +    };
I don't mind that `onPress` returns a function. This immediately invoked function isn't my favourite either `goToRouteWithParameter(Routes.ExplainFeedback, serviceId, history)();` but we use it in a lot of places .

2021-02-02 23:03 UTC, tomy-pg commented on src/components/search/search_results_component.tsx
> +              }, 0);
This `flatListRef` is different than the one used in the helper function.
This one refers to the animated flatlist: 
`const AnimatedFlatList = Animated.createAnimatedComponent(FlatList);` so the way in which scrollToOffset is retrieved is different since we have to call `getNode()` in this ref.

2021-02-03 18:00 UTC, tomy-pg commented on src/components/search/search_results_component.tsx
> +        props.saveService(service);
Sounds good. This function is actually tied to a redux action so this name change is going to go through the different layers of react and redux

2021-02-04 18:36 UTC, rasmus-storjohann-PG requested changes
Just the one typo, otherwise this is good to go

2021-02-04 18:36 UTC, rasmus-storjohann-PG commented on src/components/services/thank_you_message_or_empty_component.tsx
> +interface ThankYouMessage {
`ThankYouMessageProps`

2021-02-04 19:32 UTC, merged