Feature/issue 1350 topics scroll offset
pg-irc/pathways-frontend pull request #1367
Opened 2021-02-08 21:44 UTC by tomy-pg

2021-02-08 22:20 UTC, rasmus-storjohann-PG requested changes

2021-02-08 22:20 UTC, rasmus-storjohann-PG commented on src/components/topics/task_list_component.tsx
> +        if (this.flatListRef && hasTopicDetailPageChanged(previousProps, this.props)) {
Legibility will be improved if you do an early return on `this.flatListRef` being null.

How about if you had a local variable like so
```ts
const foo = {
                ...this.state,
                data: this.props.tasks,
                scrollOffset: this.state.scrollOffset,
            };
```
and then you could have this in one call
```ts
            return this.setState(
                            foo, 
                            (): void => scrollToOffsetWithTimeout(this.flatListRef, this.state.scrollOffset),
                    );
```
and this in the other
```ts
            return this.setState(
                     { ...foo, scrollOffset: 0}, 
                    (): void => scrollToOffsetWithTimeout(this.flatListRef, this.state.scrollOffset),
            );
```

2021-02-08 22:20 UTC, rasmus-storjohann-PG commented on src/components/topics/task_list_component.tsx
> +)
Do you need this function? it's effectively just an alias.

2021-02-08 22:26 UTC, tomy-pg commented on src/components/topics/task_list_component.tsx
> +)
Makes sense

2021-02-08 22:28 UTC, tomy-pg commented on src/components/topics/task_list_component.tsx
> +        if (this.flatListRef && hasTopicDetailPageChanged(previousProps, this.props)) {
The earlier return for `this.flatListRef` makes a lot of sense. 

As for the local variable, the values inputted into this `setState` changes in the last commit to clean it up a bit.

2021-02-09 17:09 UTC, rasmus-storjohann-PG approved these changes
I like it!

2021-02-09 23:13 UTC, merged