Feature/issue 1360 enable my location on search by default
pg-irc/pathways-frontend pull request #1371
Opened 2021-02-09 20:12 UTC by ian-lin-PG

2021-02-11 17:41 UTC, tomy-pg requested changes

2021-02-11 17:41 UTC, tomy-pg commented on src/components/search/search_input_component.tsx
> +    if (status === Permissions.PermissionStatus.UNDETERMINED) {
This condition is too restrictive. It should include `PermissionStatus.DENIED`. If a user initially denies location permission, but later decides they would like to allow it, `Permissions.askAsync` (function body in this conditional) will not be executed since their status at the time will be `DENIED`.

2021-02-11 17:41 UTC, tomy-pg commented on src/components/search/search_input_component.tsx
> +    if (status === Permissions.PermissionStatus.UNDETERMINED) {
You may want to also consider an early return on `PermissionStatus.GRANTED` to improve readability as well.

2021-02-11 17:42 UTC, tomy-pg commented on src/components/search/search_input_component.tsx
> +        <View style={{ paddingTop: 7 }}>
I appreciate this!

2021-02-11 18:13 UTC, ian-lin-PG commented on src/components/search/search_input_component.tsx
> +    if (status === Permissions.PermissionStatus.UNDETERMINED) {
The code is restrictive by design to prevent the location input field is resetting constantly otherwise. If `PermissionStatus.Granted` is used, what would be the expected behaviour. I wouldn't want to set the location input field if user has ran a search using a custom location not my location. Hm....

2021-02-16 18:23 UTC, tomy-pg requested changes

2021-02-16 18:23 UTC, tomy-pg commented on src/components/search/search_input_component.tsx
> +    askLocationPermission(props.setSearchLocationInput, props.saveSearchLocation, props.i18n);
I am not a huge fan of how this is triggered. React recommends side-effects to be done with their useEffect hook. We can also create a custom hook for this or trigger it with a callback.

2021-02-16 18:44 UTC, rasmus-storjohann-PG requested changes
Still got some way to go on this ... make sure to have a good understanding of what the non-default code path looks like so that you can match it in the new default behaviour.

2021-02-16 18:44 UTC, rasmus-storjohann-PG commented on src/components/search/search_input_component.tsx
> +    if (status === Permissions.PermissionStatus.UNDETERMINED) {
Under the SRP, components are responsible for showing state on the screen, meaning that components should not contain complex logic directly. The best place for complex logic are reducers, sagas and hooks. Does it make sense to move this logic to one of those?

2021-02-16 18:44 UTC, rasmus-storjohann-PG commented on src/components/search/search_input_component.tsx
> +                    props.onSearchRequest(props.searchTermInput, defaultLocation);
Here the component has to worry about a lot of stuff that has nothing to do with presenting the state of the app on the screen. It should not need to know or care that there are three different things going on under the hood when setting the location. It should instead be able to delegate this to a redux action. The first two are already redux actions, so does it make sense to change the reducers to have the same effect? The last triggers a saga I think? It can also be hooked up to an action. Note also that the code here needs to be consistent with what happens in the non-default case ... if it is as messy as this, they both need to be cleaned up ... if it is cleaner than this, then the same cleaner approach can be used here.

2021-02-16 22:17 UTC, ian-lin-PG commented on src/components/search/search_input_component.tsx
> +                    props.onSearchRequest(props.searchTermInput, defaultLocation);
The code block here has been removed after reviewing the UX with cherrie and melanie.

2021-02-17 19:05 UTC, rasmus-storjohann-PG requested changes

2021-02-17 19:05 UTC, rasmus-storjohann-PG commented on src/components/search/use_ask_location_permission.ts
> +};
- [ ] Make local variables for the predicates to explain what's going on
- [ ] Inline `await getPermission();` to make it clear what's the difference between the two calls to `ermissions.askAsync(Permissions.LOCATION);`

2021-02-17 19:21 UTC, rasmus-storjohann-PG commented on src/components/search/use_ask_location_permission.ts
> +export const useAskLocationPermission = (setLocationInput: LocationSetter, saveLocation: LocationSetter, i18n: I18n): void => {
One more change will make this clearer, the signature should just take a single, zero-argument callback:
```ts
export const useAskLocationPermission = (setLocationToMyLocation: () => void): void => {`
```
then you'll have just "if permission is granted, set location to my location", and all the low level i18n stuff will be in the caller.

2021-02-17 19:47 UTC, tomy-pg commented on src/components/search/use_ask_location_permission.ts
> +export const useAskLocationPermission = (setLocationInput: LocationSetter, saveLocation: LocationSetter, i18n: I18n): void => {
I like this suggestion a lot.

2021-02-17 23:20 UTC, merged