Feature/issue 1394 fix scroll offset
pg-irc/pathways-frontend pull request #1437
Opened 2021-03-09 00:00 UTC by tomy-pg

2021-03-10 00:04 UTC, rasmus-storjohann-PG commented on src/application/routing.ts
> +    memoryHistory.replace(currentEntry.pathname, currentEntryState);
This is a very important function, and it feels like it could still get a little clearer

2021-03-10 00:09 UTC, rasmus-storjohann-PG commented on src/components/bookmarks/service_bookmarks_component.tsx
> +    useServicesScrollToOffset(flatListRef, bookmarkedServicesOffset, props.bookmarkedServices);
Feels like all this hook code can still be made tidier

2021-03-10 00:10 UTC, rasmus-storjohann-PG commented on src/components/explore/explore_all_component.tsx
> +                        300,
what's the 300 again? Local variable can be used to make this clear

2021-03-10 00:12 UTC, rasmus-storjohann-PG commented on src/components/help/help_component.tsx
> +    goToRouteWithParameter(Routes.Services, props.topic.id, props.history);
Looks like this change is OK ... it certainly is a simplification, not 100% sure why the library writers encouraged the more complex pattern or whether this really came from one of the Affinity guys...

2021-03-10 00:17 UTC, rasmus-storjohann-PG commented on src/components/topics/task_list_component.tsx
> +            }, (): void => scrollToOffsetWithTimeout(this.flatListRef, this.state.scrollOffset));
I have made this suggestion before, if you have reason to not follow it, let's talk: Rename `scrollToOffsetWithTimeout()` to `scrollToOffset()`, the timeout is in my view an implementational detail that the caller does not need to worry about, so it doesn't need to be part of the function name

2021-03-10 00:23 UTC, rasmus-storjohann-PG commented on src/components/use_current_offset_from_location_for_scroll.ts
> +    }, [location.state]);
The `useLocation()` call can be made inside this hook. Even the `setState()` hook that gives you `listOffsetSetter` could be made inside this hook, I think...

2021-03-10 22:11 UTC, tomy-pg commented on src/application/__tests__/routing.test.ts
> +        expect(history.location.state).toEqual({ previousOffset });
The `history.location.state` type being of type `unknown` is a problem. 
I receive the exact same problem people in this thread face: 
https://github.com/DefinitelyTyped/DefinitelyTyped/issues/41674

Trying to access previousOffset this way does not work for this reason: 
```
Element implicitly has an 'any' type because expression of type '"previousOffset"' can't be used to index type '{}'. Property 'previousOffset' does not exist on type '{}'.ts(7053)
```
As well, our tslint does not like this:
```
object access via string literals is disallowed (no-string-literal)
```
I am opting to cast `history.location.state` as `any` so we can retrieve the previousOffset using:
`history.location.state.previousOffset` for our tests.

2021-03-10 22:35 UTC, tomy-pg commented on src/components/services/render_service_items.tsx
> +        goToRouteWithParameter(Routes.ServiceDetail, service.id, props.history, props.scrollOffset);
Specifically, the idea is that I wanted to see that the offsets worked when removing the link between redux offset and a service list component.

2021-03-10 23:10 UTC, tomy-pg commented on src/components/use_current_offset_from_location_for_scroll.ts
> +    }, [location.state]);
I have turned this into a single hook. Let me know what you think, but I think it gets the job done and its clear.

2021-03-10 23:47 UTC, tomy-pg commented on src/components/topics/task_list_component.tsx
> +            }, (): void => scrollToOffsetWithTimeout(this.flatListRef, this.state.scrollOffset));
This function is old and must have been missed in a past PR.

2021-03-10 23:48 UTC, tomy-pg commented on src/components/feedback/other_remove_service_component.tsx
> +        goToRouteWithParameter(Routes.ContactInformation, props.match.params.serviceId, memoryHistory);
Either way, the benefits of this function returning a function is only used in one component `ExploreAllComponent` whereas the advantages of not returning a function is noticed by many.

2021-03-12 18:46 UTC, rasmus-storjohann-PG requested changes

2021-03-13 00:23 UTC, merged