Feature/issue 1440 ar android crash
pg-irc/pathways-frontend pull request #1445
Opened 2021-03-17 23:33 UTC by tomy-pg

2021-03-18 22:09 UTC, rasmus-storjohann-PG requested changes

2021-03-19 21:38 UTC, rasmus-storjohann-PG requested changes
Nice, simple solution in the end. Just a couple of more suggestions

2021-03-19 21:38 UTC, rasmus-storjohann-PG commented on src/sagas/locale.ts
> +    isRTL(appLocale) || deviceAndAppAreRTL(deviceLocale, appLocale)
Boolean arithmetic my friend: A || (A && B) = A, since if B is false, A && B is false, in which case A || (A && B) is A || false which is just the same as A. If B is true, A && B is the same as A, and A || A is also the same as A. So the device locale has no effect on the computed value here.

2021-03-19 21:38 UTC, rasmus-storjohann-PG commented on src/sagas/locale.ts
> -);
OK, you figured it out

2021-03-19 21:38 UTC, rasmus-storjohann-PG commented on src/locale/effects.ts
> +export const isRTL = (locale: string): boolean => locale.toLocaleLowerCase().startsWith('ar');
Is this change needed now with the simplification? I like the old way better if it's all the same ...  having nightmares about supporting Armenian

2021-03-19 23:52 UTC, tomy-pg commented on src/sagas/locale.ts
> -);
Eventually....

2021-03-19 23:52 UTC, tomy-pg commented on src/locale/effects.ts
> +export const isRTL = (locale: string): boolean => locale.toLocaleLowerCase().startsWith('ar');
I reverted back to the old way!

2021-03-22 21:25 UTC, merged