Feature/issue 1431 province selection
pg-irc/pathways-frontend pull request #1446
Opened 2021-03-18 16:49 UTC by ian-lin-PG

2021-03-19 21:22 UTC, rasmus-storjohann-PG requested changes
Nice work, I suggested some simplifications and reorganizations.

2021-03-19 21:22 UTC, rasmus-storjohann-PG commented on src/components/welcome/welcome_component.tsx
> +                            onValueChange={props.setProvince}
"set" province or "save" province - please be consistent. I think "save" is a better antonym to "load"

2021-03-19 21:22 UTC, rasmus-storjohann-PG commented on src/province/types.ts
> +}
How come we have not needed these before? I'm worried they're duplicates of existing types. They certainly don't belong in a file that is about "province" stuff

2021-03-19 21:22 UTC, rasmus-storjohann-PG commented on src/province/types.ts
> +}
Types like this are either used in the store or created by selectors. This interface should sit in a file that is located either within the store or selector folder, in this case, it is used in both store and selector, so it should be located in the store folder. I would like to avoid having lots of specific folders at the top level under `src/`. I'm not a fan of the locale code, and that includes the current `src/locale` folder, so let's not use it as a pattern to follow.

2021-03-19 21:22 UTC, rasmus-storjohann-PG commented on src/stores/index.ts
> +    readonly province: province.ProvinceStore;
I think it's overkill to have a top level store just for this. This data can be part of the `UserExperience` store. Make sure that it's persisted as well...

2021-03-19 21:22 UTC, rasmus-storjohann-PG commented on src/stores/province/actions.ts
> +};
Is this needed?

2021-03-19 21:22 UTC, rasmus-storjohann-PG commented on src/application/styles.ts
> +    item: {
Can we get a more descriptive name for this style?

2021-03-19 21:22 UTC, rasmus-storjohann-PG commented on src/components/welcome/welcome_component.tsx
> +import { SaveProvinceAction } from '../../stores/province/actions';
How about getting both of these from `../../stores/user_profile.ts`, would that make sense?

2021-03-19 21:22 UTC, rasmus-storjohann-PG commented on src/province/types.ts
> +}
See my other comment, I suggest adding this to `/src/stores/user_profile.ts`

2021-03-19 21:22 UTC, rasmus-storjohann-PG commented on src/stores/province/index.ts
> +export const reducer = (store: ProvinceStore = buildDefaultStore(), action?: actions.ProvinceAction): ProvinceStore => {
This is overkill too, don't need a new reducer for this

2021-03-23 17:05 UTC, rasmus-storjohann-PG requested changes
Still a couple of things to fix

2021-03-25 16:28 UTC, tomy-pg commented on src/components/welcome/welcome_component.tsx
> +    if (props.currentRegion && props.currentLocale.code) {
> I would also suggest that the locale isn't actually changed until the start button has been hit

I hear you on this and is definitely something that needs to be addressed but I think this takes us away from the 'thin thread' we are aiming for, for the deadline. This functionality is tied to the `saga/locale.ts` which also covers how the language picker works in the hamburger menu. Making this change will require us to either make the same change to the hamburger menu (which currently does not have a start button) or to make a separate saga for just the welcome screen language picker.

2021-03-25 16:54 UTC, rasmus-storjohann-PG commented on src/components/welcome/welcome_component.tsx
> +    if (props.currentRegion && props.currentLocale.code) {
Valid points, @tomy-pg , I'm open with just making it work for now and merge with some known issues, including UX glitches that better separation of concerns can fix.

2021-03-25 17:01 UTC, tomy-pg commented on src/components/welcome/welcome_component.tsx
> +    if (props.currentRegion && props.currentLocale.code) {
Created an issue for this here: #1450

2021-03-25 18:59 UTC, rasmus-storjohann-PG commented on src/stores/__tests__/user_profiles.test.ts
> +            expect(newStore.region).toBe(savedRegion);
You didn't address this comment

2021-03-25 21:12 UTC, tomy-pg approved these changes

2021-03-25 22:14 UTC, merged