Feature/issue 1473 usereducer in welcome screen
pg-irc/pathways-frontend pull request #1476
Opened 2021-05-06 16:30 UTC by ian-lin-PG

2021-05-06 21:52 UTC, rasmus-storjohann-PG requested changes

2021-05-06 21:52 UTC, rasmus-storjohann-PG commented on src/application/locales.ts
> +            return [];
Throw exception here instead, it is not valid to have a different region.

2021-05-06 21:52 UTC, rasmus-storjohann-PG commented on src/validation/region/types.ts
> +export interface RegionLocaleMap {
Naming: How is this a map?

2021-05-06 21:52 UTC, rasmus-storjohann-PG commented on src/components/welcome/welcome_component.tsx
> +                    availableLocales: getAvailableLocales(action.payload.region),
Even better if the reducer rather than setting the locale to undefined, could be smart about not changing it in cases where the same locale is supported in both the old and new regions

2021-05-06 21:52 UTC, rasmus-storjohann-PG commented on src/components/welcome/welcome_component.tsx
> +                };
Under what conditions do you anticipate to hit this default? Is this how to intend to initiate the state? If so, a `buildDefaultState()` helper function would make it more clear what's going on.

2021-05-06 21:52 UTC, rasmus-storjohann-PG commented on src/components/welcome/welcome_component.tsx
> +        reducer, { region: undefined, locale: undefined, availableLocales: [] },
Is this the best value to use for the default state, or would it be better to use values passed in through the props?

2021-05-06 21:52 UTC, rasmus-storjohann-PG commented on src/components/welcome/welcome_component.tsx
> +const RegionPicker = (state: RegionLocaleMap, dispatch: Dispatch<SelectRegionAction>): JSX.Element => {
Here's a way to build a habit to pay closer attention to naming: See that you have this "map" type `RegionLocaleMap`, but in a lot of different places where you use it, you use "state" rather than "map". This indicates that "state" is a better name for the type than "map". See if you can make it a habit to pay attention to names in that way

2021-05-06 21:52 UTC, rasmus-storjohann-PG commented on src/components/welcome/welcome_component.tsx
> +                enabled={state.region ? true : false}
You can also use `!!` to convert a value to the corresponding boolean value: Negate once to convert any truthy value to false and any falsy value to true, negate again to convert any truthy value to trye and falsy value to false.

2021-05-06 21:52 UTC, rasmus-storjohann-PG commented on src/components/welcome/welcome_component.tsx
> +                        saveRegion={props.saveRegion} />
I think you can remove a lot of code if you create your `onStartButtonPress` function in this scope and pass it down to the start button component. Most of the `StartButtonProps` properties would disappear

2021-05-06 21:52 UTC, rasmus-storjohann-PG commented on src/validation/region/types.ts
> +);
These action generator functions are written just the way I thought they should, but I am a little concerned with the file that they're in. useReducer is *similar* to Redux, but it's not the same thing exactly. It is very likely that people will be confused, thinking that these are actual Redux actions. A way to reduce that confusion is to put these two functions, and the constants they use as well, inside the component file. That way people will see that they are scoped to that one file and therefore *clearly* not actual Redux actions.

2021-05-06 21:52 UTC, rasmus-storjohann-PG commented on src/validation/region/types.ts
>      readonly fallback: RegionCode;
What is this fallback thing? I think you may have been inspired by a bad pattern in the locale code, which I just removed ;-)

2021-05-06 21:53 UTC, rasmus-storjohann-PG commented
Still no unit tests on the reducer ... this is the whole point of using useReduce

2021-05-12 18:33 UTC, rasmus-storjohann-PG requested changes
I added some commits to the PR, just because this PR gave a good opportunity for me to demonstrate how to write test code, which will become very handy in upcoming on-boarding. There are some changes I would like you to make as well.

2021-05-12 18:33 UTC, rasmus-storjohann-PG commented on src/components/welcome/index.ts
> +// tslint:disable: no-this readonly-keyword no-expression-statement no-class
You can give a bit more thought to the name of this file. I would say that this file contains different kinds of things right now, so it should be split up into two or three smaller files that will be easier to give meaningful names.

2021-05-12 20:22 UTC, ian-lin-PG commented on src/components/welcome/welcome_component.tsx
>                  placeholder='Select province'
English since we decided not to update the app as the locale is changed within the welcome screen.

2021-05-14 22:45 UTC, ian-lin-PG commented on src/components/welcome/welcome_component.tsx
> +                onValueChange={(region: RegionCode): void => props.dispatch({ type: constants.SELECT_REGION, payload: { region } })}
The `dispatch` is from the `useReducer` hook. I have yet to find a way to compile without passing it down.

2021-05-17 15:07 UTC, rasmus-storjohann-PG commented on src/components/welcome/welcome_component.tsx
> +                onValueChange={(region: RegionCode): void => props.dispatch({ type: constants.SELECT_REGION, payload: { region } })}
No what I meant was this
```ts
onValueChange={(region: RegionCode): void => props.dispatch(selectRegion(region) })}
```

2021-05-17 17:35 UTC, merged