Feature/issue 1481 client upgrade
pg-irc/pathways-frontend pull request #1484
Opened 2021-05-20 17:07 UTC by ian-lin-PG

2021-05-25 22:56 UTC, brandon-PG approved these changes
Looks good to me

2021-05-25 22:57 UTC, rasmus-storjohann-PG requested changes
Really nice work, just some minor changes to suggest

2021-05-25 22:57 UTC, rasmus-storjohann-PG commented on src/components/search/search_input_component.tsx
> +        case 'none':
Shouldn't this be instead
```ts
if (status === 'none') {
    openAppSettings();
} else {
    setSearchLocationInput(i18n._(MY_LOCATION_MESSAGE_DESCRIPTOR));
}
```

2021-05-25 22:57 UTC, rasmus-storjohann-PG commented on src/components/search/use_ask_location_permission.ts
> +            const status = isAndroid() ? getPermissionResponse.android.scope : getPermissionResponse.ios.scope;
This is repeated from above, can be DRYed up

2021-05-25 22:57 UTC, rasmus-storjohann-PG commented on src/components/search/search_input_component.tsx
> +        case PermissionStatus.DENIED:
If/else still the preferred form here

2021-05-25 23:22 UTC, rasmus-storjohann-PG commented
@ian-lin-PG one more thing, can you update to use eslint and https://github.com/jonaskello/eslint-plugin-functional while you're at it?

2021-05-27 17:45 UTC, ian-lin-PG commented on src/components/search/search_input_component.tsx
> +        case 'none':
I eventually installed the expo-location package separately which has the more recognizable Permission.Status that we are more used to.

2021-05-27 17:49 UTC, ian-lin-PG commented on src/components/search/use_ask_location_permission.ts
> +            const status = isAndroid() ? getPermissionResponse.android.scope : getPermissionResponse.ios.scope;
Updated package as described as above.

2021-05-27 23:35 UTC, merged