Feature/issue 1489 add logo to header menu
pg-irc/pathways-frontend pull request #1491
Opened 2021-06-02 00:35 UTC by ian-lin-PG

2021-06-02 21:00 UTC, brandon-PG approved these changes

2021-06-02 21:54 UTC, rasmus-storjohann-PG requested changes
Just minor changes suggested

2021-06-02 21:54 UTC, rasmus-storjohann-PG commented on src/application/images.ts
> +export const pgLogo = require('../../assets/images/pg_logo.png');
peaceGeeksLogo, avoid abbreviations. MB is OK, but PG is not clear.

2021-06-02 21:54 UTC, rasmus-storjohann-PG commented on src/components/header_menu/header_menu_component.tsx
> +};
@brandon-PG you may be able to reuse this component.

2021-06-03 16:19 UTC, rasmus-storjohann-PG requested changes
Just one commit message that needs to be fixed

2021-06-03 16:19 UTC, rasmus-storjohann-PG commented on src/application/images.ts
> +export const pgLogo = require('../../assets/images/pg_logo.png');
commit message does not match code change

2021-06-03 16:31 UTC, merged