Feature/issue 1399 Add alternate name to service page
pg-irc/pathways-frontend pull request #1501
Opened 2021-06-10 20:58 UTC by brandon-PG

2021-06-11 17:53 UTC, ian-lin-PG commented on src/validation/search/__tests__/to_human_service_data.tests.ts
>                  last_verified_date: aDate(),
It may help to make a human service data builder to clean up the code. Since we are adding a new field, it may make sense to write a unit test for checking `altername_name` as well. It's quite common for this field to be undefined, so check the expected output in that case as well.

2021-06-11 17:53 UTC, ian-lin-PG commented on src/components/services/service_detail_component.tsx
> +    return <></>;
Is this an empty component, if so we have <EmptyComponent /> that we use for this purpose.

2021-06-11 17:53 UTC, ian-lin-PG commented on src/components/services/service_detail_component.tsx
> +    <Text style={[markdownStyles.body, {paddingTop: 4}]}><Trans>(aka {props.alternateName})</Trans></Text>
`<Trans>` will translate the text in between the tag, where translations exists. Generally we have the tag around hard coded app strings that we can control, we don't have translations for service data so we can remove the tag in this case.

2021-06-24 17:28 UTC, rasmus-storjohann-PG requested changes
A pretty bit change is needed in this PR

2021-06-24 17:28 UTC, rasmus-storjohann-PG commented on src/components/services/service_detail_component.tsx
> +                                <EmptyDividerComponent />
This should be a feedback component, following the pattern of the other pieces. Ian can explain in more detail what Feedback means here.

2021-06-24 17:28 UTC, rasmus-storjohann-PG commented on src/validation/search/__tests__/to_human_service_data.tests.ts
>                  last_verified_date: aDate(),
These changes are fine, but the fact that you have to make all these single line changes is a code smell, it indicates that these tests are to some degree redundant and that they all test the same thing. This breaks with DRY and SRP. If you have time, you might just read this code in detail and try to envisage how it might be changed to avoid this amount of repetition, it would be a very good exercise (but hard!)

2021-06-29 15:03 UTC, rasmus-storjohann-PG commented on src/components/services/service_detail_component.tsx
> +                />
Looks like the `Description` field is a good one to follow as a pattern for the new field you're adding. I think the change we need is just a bit of refactoring.

2021-06-29 15:05 UTC, rasmus-storjohann-PG commented on src/components/services/service_detail_component.tsx
> +    readonly isFeedbackInputEnabled: boolean;
This feels non-DRY to me ... this will also be resolved with the refactoring, I expect this props type to go away

2021-06-29 15:06 UTC, rasmus-storjohann-PG commented on src/components/services/service_detail_component.tsx
> +    if (props.alternateName) {
Oh yeah, we should also talk about our convention of preferring early returns. I should update our style guide with that....

2021-06-29 15:07 UTC, rasmus-storjohann-PG commented on src/components/services/service_detail_component.tsx
> +const EmptyDividerComponent = (): JSX.Element => (
I'm a little surprised that this is needed in this PR, but I'm open to be convinced

2021-06-29 15:08 UTC, rasmus-storjohann-PG requested changes
Still a bit of work left here, but we're getting close. This is quite a big change...

2021-06-30 22:59 UTC, merged