Feature/issue 1451 new hamburger
pg-irc/pathways-frontend pull request #1503
Opened 2021-06-15 16:22 UTC by ian-lin-PG

2021-06-15 21:55 UTC, rasmus-storjohann-PG requested changes
@ian-lin-PG excellent work on the hamburger menu. I've made a few suggestions, but they don't all have to go in now, as long as we raise another PR against this same story and fix remaining issues there right after we've pushed to staging.

2021-06-15 21:55 UTC, rasmus-storjohann-PG commented on src/application/locales.ts
> +};
This is very clean and tidy, which I like, but I am confused as to why it is needed, because we clearly already has this mapping defined in the system, see `getAvailableLocales()`. The locale management code is complex, I've already spent a lot of time cleaning this up, I don't want to throw another piece in there that makes it even more complicated.

2021-06-15 21:55 UTC, rasmus-storjohann-PG commented on src/components/header_menu/header_menu_component.tsx
> +                </TouchableOpacity>
Is there some duplication from the code above?

2021-06-15 21:55 UTC, rasmus-storjohann-PG commented on src/components/header_menu/language_drawer_component.tsx
> +            updateToken();
This is exactly the wrong way to use actions with sagas. Sagas are designed to watch the actions being emitted and respond with async calls. (In this case, we want a new push notification token post request to go to the server so that we know what locale to use when sending notifications to this user.) What is wrong here is that we have UX code that knows about this and has to make this extra call to update token. This is bad because (1) the UX code should not know or care about this, and (2) sagas, when used correctly, are exactly the right solution to this: Have the saga listen for the `setLocale` action, and respond by updating the token. Then the whole `updateToken()` action and all related prop drilling disappears and we are all happier for it.

I know that this is not new code in this PR, so you don't need to change it now ... but we want to fix this soon, and I think it should actually be pretty simple to fix, since it should mostly consist of removing code.

2021-06-15 21:55 UTC, rasmus-storjohann-PG commented on src/components/header_menu/language_drawer_component.tsx
> +    return (
https://docs.google.com/document/d/1C8A7-vdiMDFSIuR7rID8tuSM1n6SxHKmNaOLXuFcWLI/edit#heading=h.udq7bye9nrkh

2021-06-15 21:55 UTC, rasmus-storjohann-PG commented on src/components/main/main_component.tsx
> +                >
Fix white space

2021-06-15 21:55 UTC, rasmus-storjohann-PG commented on src/selectors/user_experience/select_is_language_drawer_visible.ts
> +    appStore.userExperience.languageDrawer !== LanguageDrawer.LanguageDrawerIsClosed
Sometimes it's the little things that really helps readability and code quality, would you not prefer to read this?
```ts
appStore.userExperience.languageDrawer === LanguageDrawer.LanguageDrawerIsOpen
```
Negations slows us down. Also note the inconsistent naming "Visible" vs "Open"/"Closed".

2021-06-15 21:55 UTC, rasmus-storjohann-PG commented on src/selectors/user_experience/select_is_region_drawer_visible.ts
> +    appStore.userExperience.regionDrawer !== RegionDrawer.RegionDrawerIsClosed
"visible" vs "open"/"closed" here too

2021-06-15 21:55 UTC, rasmus-storjohann-PG commented on src/validation/region/types.ts
> +            return 'British Columbia';
Defensive programming suggests a different appriach to a switch statement like this: Map MB to Manitoba, BC to British Columbia, and throw an exception in the default. That way if we add a region and forget to update this code, we know about it right away.

2021-06-17 18:47 UTC, ian-lin-PG commented on src/application/locales.ts
> +};
We should either have `LocaleCode` or `LocaleWithLabel`. The difficulty with `LocaleWithLabel` is that it's harder to set than simply `LocaleCode`. So `LocaleCode` is saved in the store, we can certainly map it inside the connected component.

That's why I only have 'RegionCode` and chose to have a similar getLabel function there.

2021-06-17 21:19 UTC, ian-lin-PG commented on src/components/main/main_component.tsx
> +                >
The tree drawers are nested together, not sure which white space?

2021-06-22 22:59 UTC, brandon-PG requested changes

2021-06-22 22:59 UTC, brandon-PG commented on src/components/header_menu/region_drawer_connected_component.tsx
> +    saveRegion: (regionCode: RegionCode): SaveRegionAction => (
Can be 1 line

2021-06-22 22:59 UTC, brandon-PG commented on src/application/styles.ts
> +export const getViewBackgroundColorForPlatform = (): string => (
The teal background on Android causes this:
![Screenshot_1624402357](https://user-images.githubusercontent.com/84804716/123010044-b0bf6d80-d372-11eb-85ab-4f1f8a0a665a.png)

2021-06-24 18:11 UTC, rasmus-storjohann-PG commented on src/components/header_menu/header_menu_component.tsx
> +                </TouchableOpacity>
Nice solution to this issue

2021-06-24 18:30 UTC, rasmus-storjohann-PG commented on src/components/header_menu/language_drawer_component.tsx
> +        <Trans>Information about British Columbia is available in the following languages:</Trans>;
You should use placeholders for region here. Also, change the text to "Information about {newRegion} is only available in {languages}, do you want to access information about {newRegion} in English?"

2021-06-24 18:41 UTC, merged