Feature/issue 1539 copy change design tweaks
pg-irc/pathways-frontend pull request #1547
Opened 2021-07-21 16:55 UTC by ian-lin-PG

2021-07-22 22:49 UTC, brandon-PG requested changes

2021-07-22 22:49 UTC, brandon-PG commented on src/components/header_menu/header_menu_component.tsx
> +        </View >
We don't add this space anywhere else

2021-07-22 22:49 UTC, brandon-PG commented on src/fixtures/hard_coded/explore.ts
> +                description: 'Supports for low income, people with disabilities, youth',
This grammar doesn't feel correct

2021-07-22 22:57 UTC, ian-lin-PG commented on src/components/header_menu/header_menu_component.tsx
> +        </View >
Good catch.

2021-07-23 00:04 UTC, brandon-PG approved these changes

2021-07-23 03:40 UTC, rasmus-storjohann-PG requested changes
Hey @ian-lin-PG sorry I didn't get to this until now. I have some suggestions, but it's mostly small stuff.

2021-07-23 03:40 UTC, rasmus-storjohann-PG commented on src/components/onboarding/onboarding_component.tsx
> +    return <BCOnboardingImages />;
This is about the commit message, you can work on making them clearer, they should be a full sentence

2021-07-23 03:40 UTC, rasmus-storjohann-PG commented on src/components/onboarding/onboarding_component.tsx
> +        titleElement: <OnboardingText text={t`BBookmark the topics that you want to save for future use.`} />,
Typo is still there. "BBookmark"

2021-07-23 03:40 UTC, rasmus-storjohann-PG commented on src/components/help/help_component.tsx
> +        <VisitManitobaStartButton />;
I'm not a fan of `:?` operators, especially when they span many lines, and especially when the boolean argument is an expression rather than just a variable. I would much prefer:
```ts
const helpButton = regionIsBc ? <FindSettlementAgencyButton /> : <VisitManitobaStartButton />;
```
but it would be nicer still to just break out a well named helper function for this. All the ternary operators in this function makes it very clear that this function does not adhere to proper separation of concerns and SRP.

2021-07-23 03:40 UTC, rasmus-storjohann-PG commented on src/components/help/help_component.tsx
> +                        {helpBodyText}
Here also, it would be much nicer to have `helpBodyText` be a function that takes the region as argument, it will make it a lot clearer what's going on, and you might even avoid the over-long line.

2021-07-23 03:40 UTC, rasmus-storjohann-PG commented on src/fixtures/hard_coded/explore.ts
> +                description: 'Supports for low income, people with disabilities, youth',
I agree, "support for low income" is not good English

2021-07-23 03:40 UTC, rasmus-storjohann-PG commented on src/components/recommended_topics/call_to_action.tsx
> +export const CallToActionPartialComponent = (props: Props): JSX.Element => (
Hmmm, what's a "partial component"? I realize this is not new code, but I hadn't seen this before...

2021-07-23 21:07 UTC, ian-lin-PG commented on src/components/recommended_topics/call_to_action.tsx
> +export const CallToActionPartialComponent = (props: Props): JSX.Element => (
It's how it's been used to describe the shortened collapse component after part of questionnaire is filled out.

2021-07-27 16:20 UTC, merged