Feature/issue 1523 bookmark services in different regions
pg-irc/pathways-frontend pull request #1551
Opened 2021-07-26 20:44 UTC by rasmus-storjohann-PG

2021-07-27 17:18 UTC, ian-lin-PG commented
Switching region after bookmarked topics doesn't crash and removes the service that is not in the same region. The booking topic still crashes.

2021-07-27 17:55 UTC, brandon-PG requested changes

2021-07-27 17:55 UTC, brandon-PG commented on src/selectors/services/filter_bookmarked_services.ts
> +import R from 'ramda';
Same issue as the other pr

2021-07-28 20:59 UTC, rasmus-storjohann-PG commented on src/selectors/services/filter_bookmarked_services.ts
> +import R from 'ramda';
Fixed @brandon-PG

2021-07-28 21:03 UTC, brandon-PG approved these changes

2021-07-28 21:04 UTC, merged