Feature/issue 1554 Search colour change
pg-irc/pathways-frontend pull request #1576
Opened 2021-08-06 22:29 UTC by brandon-PG

2021-08-09 18:03 UTC, ian-lin-PG commented
MB search page:
![Simulator Screen Shot - iPhone 12 Pro Max - 2021-08-09 at 11 01 56](https://user-images.githubusercontent.com/52009863/128752488-eb068fbd-36db-4d0a-8643-d53aba89f891.png)
BC search page:
![Simulator Screen Shot - iPhone 12 Pro Max - 2021-08-09 at 11 01 43](https://user-images.githubusercontent.com/52009863/128752507-68e7f72f-7e00-4543-977e-37515c2ef65b.png)

2021-08-09 18:06 UTC, ian-lin-PG approved these changes

2021-08-12 22:02 UTC, rasmus-storjohann-PG requested changes

2021-08-12 22:27 UTC, rasmus-storjohann-PG requested changes

2021-08-12 22:27 UTC, rasmus-storjohann-PG commented on src/components/services/service_list_location_search_component.tsx
> +const style = props.isDisabled ? [applicationStyles.searchButton, applicationStyles.disabled] : applicationStyles.searchButton;
@brandon-PG can you fix this?

2021-08-13 20:19 UTC, ian-lin-PG approved these changes

2021-08-13 20:20 UTC, merged