Feature/issue 1543 manitoba start page
pg-irc/pathways-frontend pull request #1578
Opened 2021-08-09 23:33 UTC by brandon-PG

2021-08-10 20:58 UTC, ian-lin-PG commented
Screenshot of the new page:
![Simulator Screen Shot - iPhone 12 Pro Max - 2021-08-10 at 13 57 45](https://user-images.githubusercontent.com/52009863/128934097-90b96e88-aa4b-4f42-bc2b-cfcea84dcb6e.png)

2021-08-10 20:58 UTC, ian-lin-PG approved these changes

2021-08-12 22:43 UTC, rasmus-storjohann-PG requested changes
Just minor changes needed, nice work

2021-08-12 22:43 UTC, rasmus-storjohann-PG commented on src/components/header_button/chevron_back_button_component.tsx
> +};
Other places in the app we use a left arrow for 'back', why the chevron arrow here?

2021-08-12 22:43 UTC, rasmus-storjohann-PG commented on src/components/main/header_component.tsx
> +    readonly rightButtons?: ReadonlyArray<JSX.Element>;
With this change, you have two ways of expression having no right buttons, either `undefined` or `[]`. This makes it harder to write code that checks for this condition. So just use the empty array to represent there being no right buttons.

2021-08-12 22:43 UTC, rasmus-storjohann-PG commented on src/components/main/header_component.tsx
> +        return <EmptyComponent />;
I think the existing code should just work with zero buttons, no?

2021-08-12 22:43 UTC, rasmus-storjohann-PG commented on src/components/mb_start/mb_start_connected_component.tsx
> +);
Fix white space. Also could simplify since MB components only appear in MB, so the theme could be hard-coded.

2021-08-12 22:43 UTC, rasmus-storjohann-PG commented on src/components/mb_start/mb_start_component.tsx
> +                style={{height: undefined, width: '100%', aspectRatio: backgroundAspectRatio}}
If you rename the variable from `backgroundAspectRatio` to `aspectRatio`, then you can omit the variable name:
```ts
style={{height: undefined, width: '100%', aspectRatio }}
```

2021-08-12 22:43 UTC, rasmus-storjohann-PG commented on src/components/main/header_component.tsx
> +    readonly rightButtons: ReadonlyArray<JSX.Element>;
better

2021-08-12 22:43 UTC, rasmus-storjohann-PG commented on src/components/main/header_component.tsx
> -    }
I thought so, nice!

2021-08-12 22:43 UTC, rasmus-storjohann-PG commented on src/components/mb_start/mb_start_component.tsx
> +                rightButtons={[<EmptyComponent />]}
so `                rightButtons={[]}` doesn't work?

2021-08-13 18:03 UTC, brandon-PG commented on src/components/header_button/chevron_back_button_component.tsx
> +};
The mock uses a chevron arrow

2021-08-17 18:33 UTC, rasmus-storjohann-PG requested changes

2021-08-23 17:14 UTC, rasmus-storjohann-PG requested changes
A bit of cleanup to the PR

2021-08-23 17:14 UTC, rasmus-storjohann-PG commented on src/components/explore/explore_detail_component.tsx
> +import { ChevronBackButtonComponent } from '../header_button/chevron_back_button_component';
I disagree with the decision to rename the component. Which icon it uses is an implementational detail that callers should not know or care about. The only reason for this name would be if the original back button would also still be used, but that is not the case. So rename this back to just BackButtonComponent, that will also make this PR simpler.

2021-08-23 17:14 UTC, rasmus-storjohann-PG commented on src/components/questionnaire/questionnaire_component.tsx
> +    const icon = I18nManager.isRTL ? 'chevron-left' : 'chevron-right';
This bit of code is repeated quite a bit, it would be nice to DRY this up

2021-08-24 16:39 UTC, rasmus-storjohann-PG requested changes
Just minor changes needed

2021-08-24 16:39 UTC, rasmus-storjohann-PG commented on src/components/header_button/back_button_component.tsx
> +export interface ChevronBackButtonProps {
Rename props type to match component

2021-08-24 16:39 UTC, rasmus-storjohann-PG commented on src/components/help/help_component.tsx
> +        <Icon name={I18nManager.isRTL ? 'chevron-left' : 'chevron-right'}
Use `getIconForBackButton()`

2021-08-24 16:39 UTC, rasmus-storjohann-PG commented on src/components/questionnaire/questionnaire_component.tsx
> +    const icon = I18nManager.isRTL ? 'chevron-left' : 'chevron-right';
Use `getIconForBackButton()`

2021-08-24 16:39 UTC, rasmus-storjohann-PG commented on src/components/topics/task_list_item_component.tsx
> +                    <Icon style={{ fontSize: 15 }} name={I18nManager.isRTL ? 'chevron-left' : 'chevron-right'} type='FontAwesome' />
Use `getIconForBackButton()`

2021-08-24 17:48 UTC, merged