Feature/issue 1694 region specific error
pg-irc/pathways-frontend pull request #1728
Opened 2021-11-19 22:07 UTC by brandon-PG

Needs https://github.com/pg-irc/ui-strings/pull/118 for functionality

2021-11-22 19:13 UTC, rasmus-storjohann-PG requested changes

2021-11-22 19:13 UTC, rasmus-storjohann-PG commented on src/components/error_screens/error_screen_switcher_component.tsx
> +            {bulletPoint} <Trans>Postal Code - "{postalCode}"</Trans>
I don't think this will work, the <Trans> thing works by lingui scanning the source code for the <Trans> elements and pulling out the strings. With this code, the string will be computed at run time, so too late for the translation to happen
I think we should aim for the regional dependent parts of these strings to not need translation, i.e. they should be outside <Trans> elements

2021-11-22 19:13 UTC, rasmus-storjohann-PG commented on src/components/error_screens/error_screen_switcher_component.tsx
> +            {bulletPoint} <Trans>Postal Code - "{postalCode}"</Trans>
So this should be something like 
```tsx
{bulletPoint} <Trans>Postal Code</Trans> - "{postalCode}"
```

2021-11-22 19:26 UTC, brandon-PG commented on src/components/error_screens/error_screen_switcher_component.tsx
> +            {bulletPoint} <Trans>Postal Code - "{postalCode}"</Trans>
It works with [pg-irc/ui-strings#118 ](https://github.com/pg-irc/ui-strings/pull/118) in the ui strings repo. I could use the change you suggested but its the same result

2021-11-23 22:09 UTC, rasmus-storjohann-PG requested changes

2021-11-23 22:09 UTC, rasmus-storjohann-PG commented on src/components/error_screens/error_screen_switcher_component.tsx
> +};
I know this will work, but it's complicated, in particular it is possible that this will confuse translation work needlessly, because we can make it simpler by chaning the return type to `JSX.Element` and just do `return <Trans>Street - 271 Portage Ave Winnipeg</Trans>` for the MB case and `return <Trans>1356 Kingsway Vancouver</Trans>` for the BC case.

2021-11-23 22:09 UTC, rasmus-storjohann-PG commented on src/components/organizations/organization_component.tsx
> +    readonly region: RegionCode;
With the PR that was just merged, there is now a `useRegion()` hook that would let remove some of this prop drilling, you can use it if you like

2021-11-23 22:09 UTC, rasmus-storjohann-PG commented on src/components/error_screens/error_screen_switcher_component.tsx
> +};
Same idea as for the street, just return a JSX.Element with the entire translated string

2021-11-23 22:09 UTC, rasmus-storjohann-PG commented on src/components/error_screens/error_screen_switcher_component.tsx
> +            {bulletPoint} <Trans>Postal Code - "{postalCode}"</Trans>
Actually, this is nice work, keep it the way it is, ignore my comments above.

2021-11-24 22:52 UTC, merged