Issue 1569 bookmark banner revisions
pg-irc/pathways-frontend pull request #1792
Opened 2022-01-31 17:38 UTC by brandon-PG

2022-01-31 17:41 UTC, brandon-PG commented on src/components/bookmarks/bookmarks_connected_component.tsx
> +    showBookmarkBanner: selectBookmarkBanner(store) === BookmarkBanner.BookmarkBannerIsShown,
Should I create a new selector with this logic? This selector is used in select_user_data_for_local_persistence.ts

2022-01-31 19:07 UTC, rasmus-storjohann-PG requested changes
Really nice work, please make note of the refactoring here to get a better sense of the correct way to use Redux. Some minor changes still needed

2022-01-31 19:07 UTC, rasmus-storjohann-PG commented on src/stores/user_profile.ts
> +        case constants.FINISH_WELCOME_COMPONENT:
Are there other reducers that respond to `SAVE_CURRENT_REGION` and therefore also need to respond to `FINISH_WELCOME_COMPONENT`?

2022-02-01 20:12 UTC, rasmus-storjohann-PG commented on src/stores/locale/index.ts
> +            // intended fall through
This is the part I don't understand. The finish welcome flow has the region, the locale and the flip orientation properties. I only see the region property being used. Where is the code that takes the locale and flip orientation of a finish welcome flow action and applies it to the store? This should line up with the corresponding action triggered by changing the language in the hamburger menu

2022-02-01 20:45 UTC, rasmus-storjohann-PG commented on src/stores/__tests__/locale.test.ts
> +    });
Missing tests to make sure the reducer also takes the new locale and flip orientation flags into account

2022-02-01 20:52 UTC, rasmus-storjohann-PG commented on src/stores/__tests__/user_profiles.test.ts
> +        test('is set to shown by save region action when in intial state', () => {
test name is not right

2022-02-01 20:57 UTC, rasmus-storjohann-PG commented on src/stores/__tests__/user_profiles.test.ts
> +    describe('the bookmark banner flag', () => {
The tests in this section should tell the story of how this flag is set. This means that the tests need to be in a particular order, so that it is clear that all the needed tests are there. You're very close, but not quite there and it makes the tests hard to read. Also I like to use `it()` over `test()` for readability, so you get this:
- it('is set to RegionHasNotBeenChanged by default')
- it('is set to BookmarkBannerIsShown by a save region action')
- it('is set to BookmarkBannerIsHidden by a hide banner action')
- it('is not changed by a save region action when it is already hidden')

2022-02-01 21:06 UTC, brandon-PG commented on src/stores/locale/index.ts
> +            // intended fall through
src/sagas/locale.ts are where the locales are applied

2022-02-01 21:09 UTC, rasmus-storjohann-PG commented on src/stores/locale/index.ts
> +            // intended fall through
Right, OK, that makes sense now

2022-02-01 21:13 UTC, rasmus-storjohann-PG commented on src/stores/locale/index.ts
> +            // intended fall through
So I was looking to make sure that all the fields in the new action were actually used in a reducer somewhere, which is how most actions work, but because locale is weird, those fields are actually consumed by a saga, not a reducer, so it makes sense.

2022-02-01 23:28 UTC, merged