Feature/issue 1134 add review modal
pg-irc/pathways-frontend pull request #1824
Opened 2022-03-17 18:05 UTC by brandon-PG

2022-03-17 19:57 UTC, rasmus-storjohann-PG requested changes
Very nice work

2022-03-17 19:57 UTC, rasmus-storjohann-PG commented on src/stores/__tests__/user_profiles.test.ts
> +            expect(newStore.timesAppStarted).toBe(oldStore.timesAppStarted + 1);
JS doesn't have an integer type, so all numbers are floating point, which are tricky to compare for equality

2022-03-17 19:57 UTC, rasmus-storjohann-PG commented on src/selectors/user_profile/select_times_app_started.ts
> +};
This is not our coding style for one line functions

2022-03-17 19:57 UTC, rasmus-storjohann-PG commented on src/stores/__tests__/user_profiles.test.ts
> +        });
Nice

2022-03-17 19:57 UTC, rasmus-storjohann-PG commented on src/components/main/main_connected_component.ts
> +    showReviewModal: selectTimesAppStarted(store) === 2,
I don't want that kind of low level detail in a connected component file, it should be high level "connecting" only. Make a selector that computes whether to show the modal or not. This selector can replace the existing `selectTimesAppStarted()`

2022-03-17 19:57 UTC, rasmus-storjohann-PG commented on src/stores/__tests__/user_profiles.test.ts
> +            expect(newStore.timesAppStarted).toBe(0);
that makes more sense

2022-03-17 19:57 UTC, rasmus-storjohann-PG commented on src/components/main/main_component.tsx
> +import { hasAction, requestReview } from 'expo-store-review';
Odd names for these functions, you can make better names at the point of import : `import { foo as bar, bz as fuz } from 'whatever';`

2022-03-17 19:57 UTC, rasmus-storjohann-PG commented on src/components/main/main_component.tsx
> +    }, []);
Do you think this is consistent with the single responsibility principle? Let's talk

2022-03-18 22:56 UTC, brandon-PG commented on src/components/main/main_connected_component.ts
> +    showReviewModal: selectTimesAppStarted(store) === 2,
selectTimesAppStarted in needed in `select_user_data_for_local_persistence.ts` when saving the value to persistent data. I either create another selector or keep this logic in the connected component.

2022-03-23 18:13 UTC, merged